// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJIDWJOb-UxSPATj60YoIyEHy0KwA5ruM',
    appId: '1:5966481925:web:3f27a89966d97fca3b6a6c',
    messagingSenderId: '5966481925',
    projectId: 'mestressinais',
    authDomain: 'mestressinais.firebaseapp.com',
    databaseURL: 'https://mestressinais-default-rtdb.firebaseio.com',
    storageBucket: 'mestressinais.appspot.com',
    measurementId: 'G-ZVTHZQS0EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrQYokxgMWBmSX7_wbJ-yxco5YclixxrA',
    appId: '1:5966481925:android:1e13d81aa1557e423b6a6c',
    messagingSenderId: '5966481925',
    projectId: 'mestressinais',
    databaseURL: 'https://mestressinais-default-rtdb.firebaseio.com',
    storageBucket: 'mestressinais.appspot.com',
  );
}
